
# This is a workflow is for testing feature branches
name: Branch Verification

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for all branches other than the "main" branch
  push:
    branches-ignore: 
    -  'main'
    
env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}
  FRONTEND_IMAGE_NAME: se-5g00dm04/finalProject-ahsaneve-frontend
  BACKEND_IMAGE_NAME: se-5g00dm04/finalProject-ahsaneve-backend

  
jobs:
  # This is the test job
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Name of the job as it will be displayed in GitHub
    name: Jest Tests

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Fetch code
        uses: actions/checkout@v3

      # Install node LTS version
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install the dependencies for the frontend
      - name: Install frontend dependecies
        working-directory: ./frontend
        run: npm install

      # Test the frontend code
      - name: Testing frontend project
        working-directory: ./frontend
        run: npm run test

      # Install the dependencies for the backend
      - name: Install backend dependecies
        working-directory: ./backend
        run: npm install

      # Test the backend code
      - name: Testing backend project
        working-directory: ./backend
        run: npm run test
